version: '3.3'

services:
  api:
    build: "."
    ports:
      - "3000"
    restart: "always"
    networks:
      - "api.network"
    deploy:
      replicas: 1
  nginx:
    build: "./nginx"
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - "api.network"
networks:
  api.network:

